import {useState} from "react";
import {ArrowUpRight,BriefcaseBusiness,Code2,Download,Mail,Menu,X} from "lucide-react";
import SystemScene from "../components/SystemScene";
const facts=[["4.94 / 5.00","Chemical Engineering CGPA"],["568K","transactions analysed"],["99.97%","fraud-model recall"],["63 / 1,600","Squad Hackathon 3.0"]];
const toolkit=[
["Product engineering",["JavaScript","TypeScript","React","Vite","Tailwind CSS","Node.js","Express","FastAPI","REST APIs"]],
["Data + platforms",["Python","PostgreSQL","Supabase","Firebase","Firestore","Prisma ORM","Git","GitHub","Vercel"]],
["Machine learning",["pandas","scikit-learn","XGBoost","Random Forest","SMOTE","Jupyter","Google Colab"]],
["Engineering + visualisation",["ANSYS","MATLAB","JMP","AutoCAD","Fusion 360","Blender"]]
];
const work=[
["01","Resonance","AI product intelligence","Frontend engineer · four-person team","Built the interface for a two-agent product-rating and audience-segmentation system, with Firebase Authentication and Firestore persistence.","AUTH + PERSISTENCE","React · Vite · Firebase · FastAPI · Groq","https://project-resonance.vercel.app",null],
["02","Vouch","Financial reputation","Frontend engineer · hackathon team","Built the trader dashboard, score visualisation, tier progression and live SSE updates—not the scoring model or entire product.","63RD OF 1,600","React · TypeScript · SSE · Supabase","https://vouchsignal.vercel.app/","https://github.com/SwiftDG/vouch-signal"],
["03","Neuronode","Learning system","Solo developer","Designed and built a DSA tutor that uses guided questions and stuck-point detection instead of immediately giving away answers.","SOLO BUILD","React · Node.js · Express · OpenAI API","https://neuronode.quikdb.net","https://github.com/SwiftDG/Neuronode"],
["04","Swift","Education platform","Owner · full-stack developer","Independently rebuilt and maintain this early UNILAG Chemical Engineering learning platform, currently serving 20+ real students.","20+ STUDENTS","React · JavaScript · Supabase · Python","https://swift-md.vercel.app/","https://github.com/SwiftDG/SWIFT-MD"],
["05","Fraud Detection","Applied machine learning","ML engineer · ECX project","Engineered features, applied SMOTE, compared models and evaluated a separate test set across roughly 568,000 transactions.","99.97% RECALL","Python · pandas · scikit-learn · XGBoost",null,"https://github.com/SwiftDG/credit-card-fraud-detection"]];
function Case({p}){return <article className="case"><div className="case-no">{p[0]}<span>{p[2]}</span></div><div><header><div><h3>{p[1]}</h3><small>{p[3]}</small></div><b>{p[5]}</b></header><p className="case-copy">{p[4]}</p><footer><span>{p[6]}</span><nav>{p[7]&&<a href={p[7]} target="_blank" rel="noreferrer">Live <ArrowUpRight/></a>}{p[8]&&<a href={p[8]} target="_blank" rel="noreferrer">Source <Code2/></a>}</nav></footer></div></article>}
export default function Home(){const[menuOpen,setMenuOpen]=useState(false);const closeMenu=()=>setMenuOpen(false);return <main>
<nav className="top"><a className="logo" href="#home" onClick={closeMenu}>DG<sup>/26</sup></a><div className={menuOpen?"nav-items open":"nav-items"}><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>Profile</a><a href="#contact" onClick={closeMenu}>Contact</a></div><div className="nav-actions"><a className="cv-link" href="/David_Master_CV.pdf" download>CV <Download/></a><button type="button" className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X/>:<Menu/>}</button></div></nav>
<section className="hero" id="home"><SystemScene/><div className="hero-copy"><p className="label">DAVID IZUCHUKWU GILBERT · LAGOS, NG</p><h1>I study systems.<br/>Then I build them.</h1><p className="intro">Chemical Engineering student and software developer building useful products across education, applied AI and business operations.</p><div className="actions"><a className="button" href="#work">Examine the work</a><a href="#contact">Start a project <ArrowUpRight/></a></div></div><aside><picture><source srcSet="/david-gilbert-420.webp 420w, /david-gilbert-700.webp 700w" sizes="(max-width: 800px) 290px, 360px" type="image/webp"/><img src="/david-gilbert-420.webp" width="420" height="547" fetchPriority="high" decoding="async" alt="David Izuchukwu Gilbert, Chemical Engineering student and software developer in Lagos"/></picture><small>ENGINEER / DEVELOPER<br/>AVAILABLE REMOTELY</small><p>Interested in the point where a difficult problem becomes a clear interface.</p></aside></section>
<section className="facts">{facts.map(f=><div key={f[1]}><strong>{f[0]}</strong><span>{f[1]}</span></div>)}</section>
<section className="work" id="work"><div className="section-head"><p className="label">SELECTED SYSTEMS / 2024—2026</p><h2>Selected work.<br/>Exact contributions.</h2><p>A focused selection—not my complete project history. Each file separates the product, my responsibility and the evidence.</p></div>{work.map(p=><Case key={p[1]} p={p}/>)}<a className="archive" href="/projects">More software, engineering work and experiments <b>View project archive <ArrowUpRight/></b></a></section>
<section className="toolkit" aria-labelledby="toolkit-title"><div className="toolkit-intro"><p className="label">WORKING TOOLKIT / ACROSS DISCIPLINES</p><h2 id="toolkit-title">Code, data<br/>and engineering.</h2><p>Tools I have used across shipped software, applied machine-learning work, engineering analysis and technical visualisation.</p></div><div className="toolkit-grid">{toolkit.map(([group,items],index)=><article key={group}><span>0{index+1}</span><h3>{group}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></section>
<section className="about" id="about"><div><p className="label">PROFILE / METHOD</p><h2>Engineering discipline,<br/>without the costume.</h2></div><div><p>I am a Chemical Engineering student at the University of Lagos and a self-taught full-stack developer. The disciplines meet in how I work: define the system, find the constraint, test the assumptions and make the result understandable.</p><p>I build independently and inside small teams. I can own an interface, connect it to real data, explain my decisions and say clearly what is unfinished.</p><ol><li>Understand the workflow</li><li>Build the smallest useful system</li><li>Test real behaviour</li><li>Document and improve</li></ol></div></section>
<section className="cv-panel"><div><p className="label">FULL RECORD / MASTER CV</p><h2>Education, projects,<br/>awards and experience.</h2></div><div><p>The selected case files above are only the short version. My master CV includes engineering competitions, software work, technical experience, certifications and leadership.</p><a className="button" href="/David_Master_CV.pdf" download>Download master CV <Download/></a></div></section>
<section className="contact" id="contact"><p className="label">AVAILABLE FOR FOCUSED FREELANCE WORK</p><h2>Bring the problem.<br/>We’ll define the build.</h2><p>Business websites, focused web applications and lightweight workflow automation. Scope and deliverables are agreed before development begins.</p><div className="actions"><a className="button light" href="https://wa.me/2347068349199?text=Hello%20David%2C%20I%20saw%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer">WhatsApp</a><a href="mailto:israelizuchukwu17382302@gmail.com?subject=Project%20inquiry"><Mail/> Email</a></div></section>
<div className="bottom">© {new Date().getFullYear()} DAVID GILBERT <span><a href="https://github.com/SwiftDG"><Code2/> GitHub</a><a href="https://linkedin.com/in/sarcdgdev"><BriefcaseBusiness/> LinkedIn</a></span></div>
</main>}
