import { ArrowUpRight, BriefcaseBusiness, Code2, Download, Mail } from "lucide-react";

export default function Contact() {
  return (
    <footer id="contact" className="border-t border-white/8 bg-white/[0.018]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-28">
      <div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#0b0f1a] px-6 py-14 sm:px-12 lg:px-16"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-blue-500/15 blur-3xl" /><div className="absolute -bottom-32 left-1/3 h-72 w-72 rounded-full bg-violet-500/10 blur-3xl" /><div className="relative max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-blue-300">Start a conversation</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em] text-white sm:text-6xl">Have a useful project in mind?</h2><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400">Tell me what you are trying to improve, who it is for and when you need it. I will help define a sensible first version and give you a clear next step.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="https://wa.me/2347068349199?text=Hello%20David%2C%20I%20saw%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-slate-950 hover:bg-blue-100">Message on WhatsApp <ArrowUpRight className="h-4 w-4" /></a><a href="mailto:israelizuchukwu17382302@gmail.com?subject=Project%20inquiry%20from%20your%20portfolio" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/14 bg-white/[0.04] px-6 py-3.5 text-sm font-bold text-white hover:bg-white/[0.08]"><Mail className="h-4 w-4" /> Send an email</a></div></div></div>
      <div className="mt-10 flex flex-col gap-6 border-t border-white/8 pt-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} David Izuchukwu Gilbert. Built in Lagos.</p><div className="flex flex-wrap items-center gap-5"><a href="https://github.com/SwiftDG" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 hover:text-white"><Code2 className="h-4 w-4" /> GitHub</a><a href="https://linkedin.com/in/sarcdgdev" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 hover:text-white"><BriefcaseBusiness className="h-4 w-4" /> LinkedIn</a><a href="/David_Master_CV.pdf" download className="inline-flex items-center gap-2 hover:text-white"><Download className="h-4 w-4" /> CV</a></div></div>
    </div></footer>
  );
}
